import os
import pandas as pd
from snakemake.utils import validate


# Set your specific experimental configuration here
configfile: "config/test.yaml"


# Include rules from other files
include: "rules/common.smk"
include: "rules/baseline_qc.smk"
include: "rules/qc.smk"
include: "rules/ref.smk"
include: "rules/filter.smk"
include: "rules/map.smk"


# Pseudo-rule for running analysis
rule all:
    input:
        get_input,
