import os
import pandas as pd
from Bio import SeqIO
from snakemake.utils import validate


# Set your specific experimental configuration here
configfile: "config/test.yaml"


# Include rules from other files
include: "rules/common.smk"
include: "rules/baseline_qc.smk"
include: "rules/qc.smk"
include: "rules/process_mapped.smk"


if paired:

    include: "rules/filter_paired.smk"
    include: "rules/map_paired.smk"

else:

    include: "rules/filter_unpaired.smk"
    include: "rules/map_unpaired.smk"


# Pseudo-rule for running analysis
rule all:
    input:
        get_input,
